name: CapstoneProject
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_database: ^4.1.1
  firebase_core: ^0.5.0
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1
  firebase_messaging: ^7.0.3
  flutter_spinkit: ^4.1.2+1
  flutter_automation: ^1.4.0
  shared_preferences: ^0.5.12+4

  configurable_expansion_tile: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background-image.png
    - assets/logo.png
    # - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FlutterIcons
      fonts:
        - asset: assets/fonts/FlutterIcons.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
    - family: DottiesChocolate
      fonts:
        - asset: assets/fonts/Dotties/DottiesChocolate-Black.otf
          weight: 900
        - asset: assets/fonts/Dotties/DottiesChocolate-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Dotties/DottiesChocolate-Heavy.otf
          weight: 800
        - asset: assets/fonts/Dotties/DottiesChocolate-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Dotties/DottiesChocolate-ExtraBold.otf
          weight: 700
        - asset: assets/fonts/Dotties/DottiesChocolate-ExtraBoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Dotties/DottiesChocolate-Bold.otf
          weight: 600
        - asset: assets/fonts/Dotties/DottiesChocolate-BoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Dotties/DottiesChocolate-Medium.otf
          weight: 500
        - asset: assets/fonts/Dotties/DottiesChocolate-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Dotties/DottiesChocolate-Regular.otf
          weight: 400
        - asset: assets/fonts/Dotties/DottiesChocolate-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Dotties/DottiesChocolate-Light.otf
          weight: 300
        - asset: assets/fonts/Dotties/DottiesChocolate-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Dotties/DottiesChocolate-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Dotties/DottiesChocolate-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Dotties/DottiesChocolate-Thin.otf
          weight: 100
        - asset: assets/fonts/Dotties/DottiesChocolate-ThinItalic.otf
          weight: 100
          style: italic
    - family: DottiesVanilla
      fonts:
        - asset: assets/fonts/Dotties/DottiesVanilla-Black.otf
          weight: 900
        - asset: assets/fonts/Dotties/DottiesVanilla-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Dotties/DottiesVanilla-Heavy.otf
          weight: 800
        - asset: assets/fonts/Dotties/DottiesVanilla-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Dotties/DottiesVanilla-ExtraBold.otf
          weight: 700
        - asset: assets/fonts/Dotties/DottiesVanilla-ExtraBoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Dotties/DottiesVanilla-Bold.otf
          weight: 600
        - asset: assets/fonts/Dotties/DottiesVanilla-BoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Dotties/DottiesVanilla-Medium.otf
          weight: 500
        - asset: assets/fonts/Dotties/DottiesVanilla-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Dotties/DottiesVanilla-Regular.otf
          weight: 400
        - asset: assets/fonts/Dotties/DottiesVanilla-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Dotties/DottiesVanilla-Light.otf
          weight: 300
        - asset: assets/fonts/Dotties/DottiesVanilla-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Dotties/DottiesVanilla-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Dotties/DottiesVanilla-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Dotties/DottiesVanilla-Thin.otf
          weight: 100
        - asset: assets/fonts/Dotties/DottiesVanilla-ThinItalic.otf
          weight: 100
          style: italic
        
        
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
